const members = [
  {
    name: "John Doe",
    branch: "Computer Science",
    email: "john@example.com",
    github: "johndoe",
    year: "Senior",
    hobbies: "Reading, coding",
    skills: "JavaScript, React, Node.js",
    position: "Developer",
    image: "john.jpg",
  },
  {
    name: "John Moe",
    branch: "Computer Science",
    email: "john@example.com",
    github: "johndoe",
    year: "Senior",
    hobbies: "Reading, coding",
    skills: "JavaScript, React, Node.js",
    position: "Developer",
    image: "john.jpg",
  },
  {
    name: "John Koe",
    branch: "Computer Science",
    email: "john@example.com",
    github: "johndoe",
    year: "Senior",
    hobbies: "Reading, coding",
    skills: "JavaScript, React, Node.js",
    position: "Developer",
    image: "john.jpg",
  },
  {
    name: "John Roe",
    branch: "Computer Science",
    email: "john@example.com",
    github: "johndoe",
    year: "Senior",
    hobbies: "Reading, coding",
    skills: "JavaScript, React, Node.js",
    position: "Developer",
    image: "john.jpg",
  },
  {
    name: "Jane Smith",
    branch: "Electrical Engineering",
    email: "jane@example.com",
    github: "janesmith",
    year: "Junior",
    hobbies: "Painting, swimming",
    skills: "Python, Django, SQL",
    position: "Developer",
    image: "jane.jpg",
  },
  {
    name: "Mike Johnson",
    branch: "Business Administration",
    email: "mike@example.com",
    github: "mikejohnson",
    year: "Senior",
    hobbies: "Playing guitar, hiking",
    skills: "Marketing, Sales, Management",
    position: "Logistics",
    image: "mike.jpg",
  },
  {
    name: "Emily Johnson",
    branch: "Mathematics",
    email: "emily@example.com",
    github: "emilyjohnson",
    year: "Junior",
    hobbies: "Drawing, traveling",
    skills: "Data Analysis, Statistics",
    position: "Research and Content",
    image: "emily.jpg",
  },
  {
    name: "Michael Smith",
    branch: "Physics",
    email: "michael@example.com",
    github: "michaelsmith",
    year: "Senior",
    hobbies: "Playing piano, photography",
    skills: "Quantum Mechanics, Astrophysics",
    position: "Research and Content",
    image: "michael.jpg",
  },
  {
    name: "Sara Lee",
    branch: "Chemistry",
    email: "sara@example.com",
    github: "saralee",
    year: "Junior",
    hobbies: "Cooking, hiking",
    skills: "Organic Chemistry, Biochemistry",
    position: "Logistics",
    image: "sara.jpg",
  },
  {
    name: "David Wilson",
    branch: "Environmental Science",
    email: "david@example.com",
    github: "davidwilson",
    year: "Senior",
    hobbies: "Gardening, bird watching",
    skills: "Sustainability, Climate Change",
    position: "Logistics",
    image: "david.jpg",
  },
  {
    name: "David Wilwa",
    branch: "Environmental Science",
    email: "david@example.com",
    github: "davidwilson",
    year: "Senior",
    hobbies: "Gardening, bird watching",
    skills: "Sustainability, Climate Change",
    position: "Logistics",
    image: "david.jpg",
  },
  {
    name: "David Wilsun",
    branch: "Environmental Science",
    email: "david@example.com",
    github: "davidwilson",
    year: "Senior",
    hobbies: "Gardening, bird watching",
    skills: "Sustainability, Climate Change",
    position: "Logistics",
    image: "david.jpg",
  },
  {
    name: "David Baeckon",
    branch: "Environmental Science",
    email: "david@example.com",
    github: "davidwilson",
    year: "Senior",
    hobbies: "Gardening, bird watching",
    skills: "Sustainability, Climate Change",
    position: "Logistics",
    image: "david.jpg",
  },
  {
    name: "David Pagl",
    branch: "Environmental Science",
    email: "david@example.com",
    github: "davidwilson",
    year: "Senior",
    hobbies: "Gardening, bird watching",
    skills: "Sustainability, Climate Change",
    position: "Logistics",
    image: "david.jpg",
  },
  {
    name: "Jessica Brown",
    branch: "Sociology",
    email: "jessica@example.com",
    github: "jessicabrown",
    year: "Junior",
    hobbies: "Writing, yoga",
    skills: "Social Research, Data Collection",
    position: "Research and Content",
    image: "jessica.jpg",
  },
  // Your member data
];

export default members;
